# Create a new countdown clock with
# 5000 seconds
POST http://localhost:5000/countdown/api/v1
Content-Type: application/json

{"total": "150"}

# Set id
:id = 224489a4-799d-4960-9dd1-56c4b81d1c2e

# Start
PATCH http://localhost:5000/countdown/api/v1/start/:id

# Stop
PATCH http://localhost:5000/countdown/api/v1/stop/:id

# Reset
PATCH http://localhost:5000/countdown/api/v1/reset/:id

# GET
GET http://localhost:5000/countdown/api/v1/:id


# GET
GET http://localhost:5000/worldclock

# POST
POST http://localhost:5000/worldclock
